### ISSUE TITLE
Installation issue windows on arm errorcode1206

### ISSUE THREAD

**Issue by Tigerpanzer02** [Uninett/eduroam-supplicant-win#45]
Hi,

I am using the surface pro x sq2 and tried to connect with your app, but I am always getting the issue shown in the screenshot.

![image](https://github.com/geteduroam/windows-app/assets/37453987/6f08734e-ec9c-4fff-b49e-6d9e91118849)

I already tried to reset the network adapter, remove known networks and reset the pc. Nothing helped. Running Windows 11.

**Comment by pauldekkers** [comment]
Can you try with the last version:

https://github.com/geteduroam/windows-app/releases/tag/v4.1.3

And the -arm specific binary?

**Comment by pauldekkers** [comment]
I do hope this specific build for geteduroam on Arm helped you; if not, please let us know/re-open the issue.
