### ISSUE TITLE
Signature certificate expired

### ISSUE THREAD

**Issue by gswdkks** [Uninett/eduroam-supplicant-win#46]
The signature certificate is expired since January, 2023. 
Is it possible to renew it?

**Comment by pauldekkers** [comment]
Can you elaborate on what signature is expired?

We sign the .exe's with timestamping, so no expiration should matter in that aspect. If it's an individual profile from eduroam CAT, that's an entirely different thing we need to look at.

**Comment by gswdkks** [comment]
Yes, I meant the signature certificate of the .exe application. 
I guess, that I found the cause. I try to allow the application in Microsoft Applocker, but it can't read the signature certificate. 

I read, that this is a known issue, when the root CA of the certificate is not trusted by the system. So I guess, that it's a problem, caused by Microsoft...

**Comment by pauldekkers** [comment]
Can you check if this is any different with the newly released binaries,

https://github.com/geteduroam/windows-app/releases/tag/v4.1.3

I tried to sign them in a slightly different way. Maybe it makes no difference.

**Comment by pauldekkers** [comment]
I do hope that the issue is resolved, possibly with the 4.1.3 binaries. Otherwise, please re-open/let us know.
