### ISSUE TITLE
Certificate deletion alert message after certificate has been installed

### ISSUE THREAD

**Issue by cma84** [Uninett/eduroam-supplicant-win#48]
In the process of setting up the profile using geteduroam, after installing the certificate, the next screen asks for the credentials, but when you click on connect, a warning message appears asking if you want to delete the certificate that was installed in the previous step.

![image](https://github.com/geteduroam/windows-app/assets/98520837/c1534530-45f4-4b3b-bac5-b7141813bff8)

This message can be confusing for the end user, it may even delete the certificate but then asks again if you want to install the certificate.

We hope that this bug will be resolved.

**Comment by pauldekkers** [comment]
Can you indicate what (CAT) profile this occurs with?

**Comment by cma84** [comment]
> Can you indicate what (CAT) profile this occurs with?

Universidad Autónoma de Madrid
UAM - WiFi (profile)

**Comment by pauldekkers** [comment]
We think this is resolved in version 4.1.3. You can download signed executables at
https://github.com/geteduroam/windows-app/releases/tag/v4.1.3

Hope you can confirm it. After some more testing, we'll update the regular download locations.

**Comment by cma84** [comment]
> We think this is resolved in version 4.1.3. You can download signed executables at https://github.com/geteduroam/windows-app/releases/tag/v4.1.3
> 
> Hope you can confirm it. After some more testing, we'll update the regular download locations.

Thanks
Bug fixed in that version.

One question, on the geteduroam website you can still download the 4.1.0 version. 
When will 4.1.3 be available for download on the main website?

regards

**Comment by pauldekkers** [comment]
Last time I checked the link via geteduroam.app goes to https://dl.eduroam.app/windows/x86_64/geteduroam.exe and that is 4.1.3.

Do you use a different source?

Oh and thanks for confirming it resolves the issue!

**Comment by cma84** [comment]
It is indeed 4.1.3.

I must have made a mistake running some old .exe.

Perfect, we can close this issue.

I will proceed to update the manuals for end users.

Regards.
